version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5335:5335"
    volumes:
      - ./server:/app


  admin:
    build: 
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8081:4173"
    volumes:
      - ./admin:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8082:4173"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - server
